name: Auto-update site

on:
  schedule:   # every 15 min
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with: { python-version: '3.x' }

      - name: Install notebook deps
        run: pip install papermill requests pandas matplotlib

      - name: Execute chart notebook
        run: |
          papermill notebooks/update_chart.ipynb notebooks/output.ipynb --cwd .

      - name: Commit & push images
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/assets/e7/octant_tx_month.png
          git commit -m "chore: update octant_tx_month chart" || echo "No changes"
          git push origin main
